apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/sajawalkhan01/civicpulse-backend
    newTag: prod
  - name: ghcr.io/sajawalkhan01/civicpulse-frontend
    newTag: prod
