"""create complaints table

Revision ID: eb6e47716d86
Revises: 
Create Date: 2026-09-19 23:56:00.595658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6e47716d86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('reporter_contact', sa.String(length=200), nullable=True),
    sa.Column('category', sa.Enum('water', 'electricity', 'sanitation', 'roads', 'streetlights', 'other', name='complaint_category'), nullable=False),
    sa.Column('priority', sa.Enum('high', 'normal', 'low', name='complaint_priority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'rejected', name='complaint_status'), server_default=sa.text("'open'"), nullable=False),
    sa.Column('ai_summary', sa.String(length=140), nullable=True),
    sa.Column('triaged_by', sa.String(length=50), nullable=False),
    sa.Column('triage_latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(location) BETWEEN 3 AND 200', name='ck_complaints_location_length'),
    sa.CheckConstraint('char_length(text) BETWEEN 10 AND 2000', name='ck_complaints_text_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_complaints_created_at', 'complaints', ['created_at'], unique=False)
    op.create_index('ix_complaints_status_priority', 'complaints', ['status', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_complaints_status_priority', table_name='complaints')
    op.drop_index('ix_complaints_created_at', table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
